/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.packages

class GithubLib {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun sayHello(): String {
        return "Hello from github package"
    }
}
