/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.packages

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class GithubLibTest {
    @Test
    fun testSayName() {
        val lib = GithubLib()
        assertEquals("Hello lib v0.3", lib.sayHello())
    }
}
