/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.packages

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

    @Test
    fun testSayName() {
        val lib = Library()
        assertEquals("Github Package", lib.sayName())
    }
}
